#This files store variables that can be read by snakemake

assembly : "dm6"
paired_end : False
accession_list : './NCBI_accession_list.txt'
download_transcriptome : True
whippet_bin_folder : /home/curso/miniconda3/envs/julia_0.6.1/share/julia/site/v0.6/Whippet/bin
